import { seedFromString } from './rng.js';

/**
 * The scripted campaign: fixed-seed mazes, so every player gets the exact
 * same layout and questions for a given chapter (and can compare times/
 * share codes), while still being generated by the same engine as endless
 * mode rather than hand-drawn cell by cell.
 */
export const CHAPTERS = [
  { id: 'crypt', name: 'La Crypte', width: 6, height: 6, gateCount: 2, secretCount: 1, maxDifficulty: 1 },
  { id: 'archives', name: 'Les Archives', width: 8, height: 7, gateCount: 3, secretCount: 1, maxDifficulty: 1 },
  { id: 'cloitre', name: 'Le Cloître', width: 9, height: 8, gateCount: 4, secretCount: 2, maxDifficulty: 2 },
  { id: 'donjon', name: 'Le Donjon', width: 10, height: 9, gateCount: 5, secretCount: 2, maxDifficulty: 2 },
  { id: 'oubliettes', name: 'Les Oubliettes', width: 11, height: 10, gateCount: 6, secretCount: 3, maxDifficulty: 3 },
  { id: 'tour', name: 'La Tour de Garde', width: 12, height: 10, gateCount: 7, secretCount: 3, maxDifficulty: 3 },
  { id: 'sanctuaire', name: 'Le Sanctuaire', width: 13, height: 11, gateCount: 8, secretCount: 4, maxDifficulty: 3 },
].map((chapter) => ({ ...chapter, seed: seedFromString(`kinetik-labyrinth-${chapter.id}`) }));

export function findChapter(id) {
  return CHAPTERS.find((c) => c.id === id) ?? null;
}

export function nextChapter(id) {
  const index = CHAPTERS.findIndex((c) => c.id === id);
  return index >= 0 && index + 1 < CHAPTERS.length ? CHAPTERS[index + 1] : null;
}
