import { seedFromString } from './rng.js';

/**
 * The scripted campaign: fixed-seed mazes, so every player gets the exact
 * same layout and questions for a given chapter (and can compare times/
 * share codes), while still being generated by the same engine as endless
 * mode rather than hand-drawn cell by cell.
 */
/**
 * Each chapter is larger, more branched and darker than the last. `vision` is
 * how many cells the torch lights around the player (null = the whole maze is
 * visible); `hintBudget` caps hints per attempt; `minDifficulty`..`maxDifficulty`
 * is the question range used on the 'auto' setting.
 */
export const CHAPTERS = [
  { id: 'crypt', name: 'La Crypte', width: 9, height: 7, gateCount: 3, secretCount: 1, minDifficulty: 1, maxDifficulty: 2, vision: null, hintBudget: 2 },
  { id: 'archives', name: 'Les Archives', width: 11, height: 8, gateCount: 4, secretCount: 2, minDifficulty: 1, maxDifficulty: 2, vision: null, hintBudget: 2 },
  { id: 'cloitre', name: 'Le Cloître', width: 13, height: 9, gateCount: 5, secretCount: 2, minDifficulty: 2, maxDifficulty: 3, vision: 4, hintBudget: 2 },
  { id: 'donjon', name: 'Le Donjon', width: 15, height: 10, gateCount: 6, secretCount: 3, minDifficulty: 2, maxDifficulty: 3, vision: 4, hintBudget: 1 },
  { id: 'oubliettes', name: 'Les Oubliettes', width: 17, height: 11, gateCount: 7, secretCount: 3, minDifficulty: 3, maxDifficulty: 3, vision: 3, hintBudget: 1 },
  { id: 'tour', name: 'La Tour de Garde', width: 19, height: 12, gateCount: 8, secretCount: 4, minDifficulty: 3, maxDifficulty: 3, vision: 3, hintBudget: 1 },
  { id: 'sanctuaire', name: 'Le Sanctuaire', width: 21, height: 13, gateCount: 10, secretCount: 4, minDifficulty: 3, maxDifficulty: 3, vision: 2, hintBudget: 1 },
].map((chapter) => ({ ...chapter, seed: seedFromString(`kinetik-labyrinth-${chapter.id}`) }));

export function findChapter(id) {
  return CHAPTERS.find((c) => c.id === id) ?? null;
}

export function nextChapter(id) {
  const index = CHAPTERS.findIndex((c) => c.id === id);
  return index >= 0 && index + 1 < CHAPTERS.length ? CHAPTERS[index + 1] : null;
}
