/**
 * The question bank behind every gate and secret passage in the Labyrinth.
 * Multiple choice only — free text would need fuzzy/locale-aware matching to
 * avoid punishing a player for an accent or a typo, which isn't worth it here.
 *
 * `category`: 'histoire' | 'sciences' | 'geographie' | 'art' | 'logique'
 * `difficulty`: 1 (facile) to 3 (difficile)
 * `choices[answer]` is always the correct one; the UI shuffles display order.
 */
export const QUESTIONS = [
  // --- Histoire ---------------------------------------------------------
  { id: 'h01', category: 'histoire', difficulty: 1, prompt: 'En quelle année a eu lieu la prise de la Bastille ?', choices: ['1789', '1799', '1804', '1815'], answer: 0 },
  { id: 'h02', category: 'histoire', difficulty: 1, prompt: 'Qui a été le premier empereur des Français ?', choices: ['Louis XIV', 'Napoléon Bonaparte', 'Charlemagne', 'Napoléon III'], answer: 1 },
  { id: 'h03', category: 'histoire', difficulty: 2, prompt: 'Quel traité met fin à la Première Guerre mondiale ?', choices: ['Traité de Westphalie', 'Traité de Versailles', 'Traité de Vienne', 'Traité de Rome'], answer: 1 },
  { id: 'h04', category: 'histoire', difficulty: 1, prompt: 'En quelle année le mur de Berlin est-il tombé ?', choices: ['1987', '1989', '1991', '1993'], answer: 1 },
  { id: 'h05', category: 'histoire', difficulty: 2, prompt: 'Qui était pharaon d’Égypte au moment de la construction de la grande pyramide de Gizeh ?', choices: ['Ramsès II', 'Khéops', 'Toutânkhamon', 'Akhenaton'], answer: 1 },
  { id: 'h06', category: 'histoire', difficulty: 1, prompt: 'Quel roi de France est surnommé le "Roi Soleil" ?', choices: ['Louis XIII', 'Louis XIV', 'Louis XV', 'Louis XVI'], answer: 1 },
  { id: 'h07', category: 'histoire', difficulty: 2, prompt: 'En quelle année a débuté la Révolution française ?', choices: ['1776', '1789', '1792', '1804'], answer: 1 },
  { id: 'h08', category: 'histoire', difficulty: 2, prompt: 'Quel empire romain tombe en 476 après J.-C. ?', choices: ['L’Empire romain d’Orient', 'L’Empire romain d’Occident', 'L’Empire byzantin', 'L’Empire carolingien'], answer: 1 },
  { id: 'h09', category: 'histoire', difficulty: 3, prompt: 'Quelle bataille marque la défaite finale de Napoléon en 1815 ?', choices: ['Austerlitz', 'Trafalgar', 'Waterloo', 'Iéna'], answer: 2 },
  { id: 'h10', category: 'histoire', difficulty: 1, prompt: 'Qui a peint la Chapelle Sixtine ?', choices: ['Léonard de Vinci', 'Raphaël', 'Michel-Ange', 'Donatello'], answer: 2 },
  { id: 'h11', category: 'histoire', difficulty: 2, prompt: 'Quel explorateur est crédité de l’arrivée européenne en Amérique en 1492 ?', choices: ['Vasco de Gama', 'Christophe Colomb', 'Fernand de Magellan', 'Jacques Cartier'], answer: 1 },
  { id: 'h12', category: 'histoire', difficulty: 2, prompt: 'Quelle civilisation a construit Machu Picchu ?', choices: ['Les Aztèques', 'Les Mayas', 'Les Incas', 'Les Olmèques'], answer: 2 },
  { id: 'h13', category: 'histoire', difficulty: 1, prompt: 'En quelle année a eu lieu le débarquement de Normandie ?', choices: ['1940', '1942', '1944', '1945'], answer: 2 },
  { id: 'h14', category: 'histoire', difficulty: 2, prompt: 'Qui était Jeanne d’Arc ?', choices: ['Une reine de France', 'Une figure militaire ayant aidé Charles VII', 'Une philosophe des Lumières', 'Une résistante de 1944'], answer: 1 },
  { id: 'h15', category: 'histoire', difficulty: 3, prompt: 'Quelle dynastie chinoise a fait construire la Grande Muraille dans sa forme la plus connue ?', choices: ['Han', 'Tang', 'Ming', 'Qing'], answer: 2 },
  { id: 'h16', category: 'histoire', difficulty: 1, prompt: 'Qui a formulé la Déclaration d’indépendance des États-Unis en 1776 ?', choices: ['George Washington', 'Thomas Jefferson', 'Benjamin Franklin', 'Abraham Lincoln'], answer: 1 },
  { id: 'h17', category: 'histoire', difficulty: 2, prompt: 'Quel mur séparait Berlin-Est et Berlin-Ouest pendant la Guerre froide ?', choices: ['Le mur de Berlin', 'La ligne Maginot', 'Le rideau de fer', 'Le mur d’Hadrien'], answer: 0 },
  { id: 'h18', category: 'histoire', difficulty: 3, prompt: 'Quel congrès réorganise l’Europe après la chute de Napoléon ?', choices: ['Le congrès de Vienne', 'Le congrès de Berlin', 'Le congrès de Paris', 'Le congrès de Vérone'], answer: 0 },
  { id: 'h19', category: 'histoire', difficulty: 1, prompt: 'Quel président français a lancé l’Appel du 18 juin 1940 ?', choices: ['Philippe Pétain', 'Charles de Gaulle', 'Georges Clemenceau', 'Léon Blum'], answer: 1 },
  { id: 'h20', category: 'histoire', difficulty: 2, prompt: 'Quelle ancienne civilisation a inventé l’écriture cunéiforme ?', choices: ['Les Égyptiens', 'Les Sumériens', 'Les Phéniciens', 'Les Perses'], answer: 1 },
  { id: 'h21', category: 'histoire', difficulty: 2, prompt: 'En quelle année l’Homme a-t-il marché sur la Lune pour la première fois ?', choices: ['1965', '1969', '1972', '1975'], answer: 1 },
  { id: 'h22', category: 'histoire', difficulty: 3, prompt: 'Quel philosophe grec fut le précepteur d’Alexandre le Grand ?', choices: ['Socrate', 'Platon', 'Aristote', 'Pythagore'], answer: 2 },
  { id: 'h23', category: 'histoire', difficulty: 1, prompt: 'Quel peuple a construit le Colisée de Rome ?', choices: ['Les Grecs', 'Les Romains', 'Les Étrusques', 'Les Carthaginois'], answer: 1 },
  { id: 'h24', category: 'histoire', difficulty: 2, prompt: 'Quelle reine d’Égypte s’est alliée à Marc Antoine ?', choices: ['Néfertiti', 'Hatchepsout', 'Cléopâtre', 'Néfertari'], answer: 2 },
  { id: 'h25', category: 'histoire', difficulty: 2, prompt: 'Quel événement déclenche la Première Guerre mondiale en 1914 ?', choices: ['L’invasion de la Pologne', 'L’assassinat de François-Ferdinand', 'Le traité de Versailles', 'La crise de Cuba'], answer: 1 },
  { id: 'h26', category: 'histoire', difficulty: 3, prompt: 'Qui fut le premier président de la Ve République française ?', choices: ['Georges Pompidou', 'Charles de Gaulle', 'François Mitterrand', 'Vincent Auriol'], answer: 1 },
  { id: 'h27', category: 'histoire', difficulty: 1, prompt: 'Quel navire britannique a coulé en 1912 après avoir heurté un iceberg ?', choices: ['Le Lusitania', 'Le Titanic', 'Le Queen Mary', 'Le Britannic'], answer: 1 },
  { id: 'h28', category: 'histoire', difficulty: 2, prompt: 'Quelle guerre a opposé le Nord et le Sud des États-Unis au 19e siècle ?', choices: ['La guerre d’indépendance', 'La guerre de Sécession', 'La guerre hispano-américaine', 'La guerre de 1812'], answer: 1 },
  { id: 'h29', category: 'histoire', difficulty: 2, prompt: 'Quel empereur a fait codifier le droit romain dans le Code civil français ?', choices: ['Louis XIV', 'Napoléon Bonaparte', 'Napoléon III', 'Charlemagne'], answer: 1 },
  { id: 'h30', category: 'histoire', difficulty: 3, prompt: 'Quelle cité grecque antique était rivale d’Athènes et réputée pour ses guerriers ?', choices: ['Corinthe', 'Thèbes', 'Sparte', 'Delphes'], answer: 2 },

  // --- Sciences -----------------------------------------------------------
  { id: 's01', category: 'sciences', difficulty: 1, prompt: 'Quelle est la planète la plus proche du Soleil ?', choices: ['Vénus', 'Mercure', 'Mars', 'la Terre'], answer: 1 },
  { id: 's02', category: 'sciences', difficulty: 1, prompt: 'Quel gaz les plantes absorbent-elles principalement lors de la photosynthèse ?', choices: ['Oxygène', 'Azote', 'Dioxyde de carbone', 'Hydrogène'], answer: 2 },
  { id: 's03', category: 'sciences', difficulty: 2, prompt: 'Quel scientifique a formulé la théorie de la relativité générale ?', choices: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Max Planck'], answer: 1 },
  { id: 's04', category: 'sciences', difficulty: 1, prompt: 'Combien d’os compte le corps humain adulte, environ ?', choices: ['106', '156', '206', '256'], answer: 2 },
  { id: 's05', category: 'sciences', difficulty: 2, prompt: 'Quel est le symbole chimique de l’or ?', choices: ['Ag', 'Au', 'Fe', 'Or'], answer: 1 },
  { id: 's06', category: 'sciences', difficulty: 1, prompt: 'Quelle est l’unité de mesure de la force dans le Système international ?', choices: ['Le watt', 'Le joule', 'Le newton', 'Le pascal'], answer: 2 },
  { id: 's07', category: 'sciences', difficulty: 2, prompt: 'Quel organe humain produit l’insuline ?', choices: ['Le foie', 'Le pancréas', 'Les reins', 'La rate'], answer: 1 },
  { id: 's08', category: 'sciences', difficulty: 2, prompt: 'Quelle particule porte une charge électrique négative ?', choices: ['Le proton', 'Le neutron', 'L’électron', 'Le photon'], answer: 2 },
  { id: 's09', category: 'sciences', difficulty: 1, prompt: 'Quel est l’état de la matière de la glace ?', choices: ['Liquide', 'Gazeux', 'Solide', 'Plasma'], answer: 2 },
  { id: 's10', category: 'sciences', difficulty: 2, prompt: 'Combien de chromosomes possède une cellule humaine normale ?', choices: ['23', '46', '48', '92'], answer: 1 },
  { id: 's11', category: 'sciences', difficulty: 1, prompt: 'Quelle planète est surnommée la "planète rouge" ?', choices: ['Vénus', 'Jupiter', 'Mars', 'Saturne'], answer: 2 },
  { id: 's12', category: 'sciences', difficulty: 3, prompt: 'Quelle est la vitesse approximative de la lumière dans le vide ?', choices: ['3 000 km/s', '30 000 km/s', '300 000 km/s', '3 000 000 km/s'], answer: 2 },
  { id: 's13', category: 'sciences', difficulty: 2, prompt: 'Quel savant a découvert la pénicilline ?', choices: ['Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Robert Koch'], answer: 1 },
  { id: 's14', category: 'sciences', difficulty: 2, prompt: 'Quel métal est liquide à température ambiante ?', choices: ['Le plomb', 'Le mercure', 'L’étain', 'Le zinc'], answer: 1 },
  { id: 's15', category: 'sciences', difficulty: 1, prompt: 'Quel est le plus grand organe du corps humain ?', choices: ['Le foie', 'Le cerveau', 'La peau', 'Le cœur'], answer: 2 },
  { id: 's16', category: 'sciences', difficulty: 2, prompt: 'Quelle scientifique a reçu deux prix Nobel dans deux disciplines différentes ?', choices: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace', 'Lise Meitner'], answer: 1 },
  { id: 's17', category: 'sciences', difficulty: 3, prompt: 'Quelle loi physique énonce que l’énergie ne se crée ni ne se détruit ?', choices: ['La loi de la gravitation', 'La loi de conservation de l’énergie', 'La loi d’Ohm', 'La loi de Hooke'], answer: 1 },
  { id: 's18', category: 'sciences', difficulty: 1, prompt: 'Quel gaz les êtres humains rejettent-ils en expirant, en plus grande quantité qu’à l’inspiration ?', choices: ['Oxygène', 'Azote', 'Dioxyde de carbone', 'Hydrogène'], answer: 2 },
  { id: 's19', category: 'sciences', difficulty: 2, prompt: 'Quel est le nom de la galaxie qui contient notre système solaire ?', choices: ['Andromède', 'La Voie lactée', 'Le Triangle', 'Le Grand Nuage de Magellan'], answer: 1 },
  { id: 's20', category: 'sciences', difficulty: 3, prompt: 'Quelle structure moléculaire porte l’information génétique ?', choices: ['L’ARN messager', 'L’ADN', 'Les protéines', 'Les lipides'], answer: 1 },
  { id: 's21', category: 'sciences', difficulty: 1, prompt: 'Combien de temps la Terre met-elle environ pour faire le tour du Soleil ?', choices: ['24 heures', '30 jours', '365 jours', '10 ans'], answer: 2 },
  { id: 's22', category: 'sciences', difficulty: 2, prompt: 'Quel physicien a énoncé les trois lois du mouvement classique ?', choices: ['Galilée', 'Isaac Newton', 'Johannes Kepler', 'James Clerk Maxwell'], answer: 1 },
  { id: 's23', category: 'sciences', difficulty: 2, prompt: 'Quelle est la plus petite unité de la matière qui garde les propriétés d’un élément ?', choices: ['La molécule', 'L’atome', 'Le quark', 'L’ion'], answer: 1 },
  { id: 's24', category: 'sciences', difficulty: 1, prompt: 'Quel sens humain est associé aux oreilles ?', choices: ['La vue', 'L’ouïe', 'L’odorat', 'Le toucher'], answer: 1 },
  { id: 's25', category: 'sciences', difficulty: 3, prompt: 'Quel phénomène explique la couleur bleue du ciel ?', choices: ['La réfraction', 'La diffusion de Rayleigh', 'L’effet Doppler', 'La polarisation'], answer: 1 },
  { id: 's26', category: 'sciences', difficulty: 1, prompt: 'Quel animal est le plus grand mammifère actuel ?', choices: ['L’éléphant d’Afrique', 'La baleine bleue', 'Le rhinocéros blanc', 'La girafe'], answer: 1 },
  { id: 's27', category: 'sciences', difficulty: 2, prompt: 'Quel est le pH approximatif de l’eau pure à 25°C ?', choices: ['3', '7', '10', '14'], answer: 1 },
  { id: 's28', category: 'sciences', difficulty: 2, prompt: 'Quel naturaliste a formulé la théorie de l’évolution par sélection naturelle ?', choices: ['Gregor Mendel', 'Charles Darwin', 'Jean-Baptiste Lamarck', 'Alfred Wallace seul'], answer: 1 },
  { id: 's29', category: 'sciences', difficulty: 3, prompt: 'Quelle particule médiatrice de la force électromagnétique est sans masse ?', choices: ['Le gluon', 'Le boson de Higgs', 'Le photon', 'Le neutrino'], answer: 2 },
  { id: 's30', category: 'sciences', difficulty: 1, prompt: 'Quel instrument sert à mesurer la température ?', choices: ['Le baromètre', 'Le thermomètre', 'L’hygromètre', 'L’anémomètre'], answer: 1 },

  // --- Géographie -----------------------------------------------------------
  { id: 'g01', category: 'geographie', difficulty: 1, prompt: 'Quelle est la capitale de l’Australie ?', choices: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answer: 2 },
  { id: 'g02', category: 'geographie', difficulty: 1, prompt: 'Quel est le plus grand océan du monde ?', choices: ['L’Atlantique', 'L’Indien', 'Le Pacifique', 'L’Arctique'], answer: 2 },
  { id: 'g03', category: 'geographie', difficulty: 2, prompt: 'Quel fleuve traverse l’Égypte ?', choices: ['Le Niger', 'Le Nil', 'Le Congo', 'Le Zambèze'], answer: 1 },
  { id: 'g04', category: 'geographie', difficulty: 1, prompt: 'Quelle chaîne de montagnes sépare l’Europe de l’Asie ?', choices: ['Les Alpes', 'L’Oural', 'Les Carpates', 'Le Caucase'], answer: 1 },
  { id: 'g05', category: 'geographie', difficulty: 2, prompt: 'Quel est le plus petit État du monde par la superficie ?', choices: ['Monaco', 'Saint-Marin', 'Le Vatican', 'Le Liechtenstein'], answer: 2 },
  { id: 'g06', category: 'geographie', difficulty: 1, prompt: 'Dans quel pays se trouve la tour Eiffel ?', choices: ['Italie', 'France', 'Espagne', 'Belgique'], answer: 1 },
  { id: 'g07', category: 'geographie', difficulty: 2, prompt: 'Quel désert est le plus grand désert chaud du monde ?', choices: ['Le désert de Gobi', 'Le Sahara', 'Le désert d’Atacama', 'Le désert du Kalahari'], answer: 1 },
  { id: 'g08', category: 'geographie', difficulty: 1, prompt: 'Quelle est la capitale du Japon ?', choices: ['Osaka', 'Kyoto', 'Tokyo', 'Yokohama'], answer: 2 },
  { id: 'g09', category: 'geographie', difficulty: 2, prompt: 'Quel pays possède le plus grand nombre de fuseaux horaires terrestres ?', choices: ['Les États-Unis', 'La Russie', 'La Chine', 'Le Canada'], answer: 1 },
  { id: 'g10', category: 'geographie', difficulty: 1, prompt: 'Quelle montagne est le plus haut sommet du monde ?', choices: ['Le K2', 'Le mont Blanc', 'L’Everest', 'Le Kilimandjaro'], answer: 2 },
  { id: 'g11', category: 'geographie', difficulty: 2, prompt: 'Quel pays a pour capitale Ottawa ?', choices: ['Les États-Unis', 'Le Canada', 'L’Australie', 'La Nouvelle-Zélande'], answer: 1 },
  { id: 'g12', category: 'geographie', difficulty: 1, prompt: 'Quel continent abrite le Sahara ?', choices: ['Asie', 'Afrique', 'Amérique du Sud', 'Océanie'], answer: 1 },
  { id: 'g13', category: 'geographie', difficulty: 2, prompt: 'Quelle mer borde la Grèce à l’est ?', choices: ['La mer Noire', 'La mer Égée', 'La mer Adriatique', 'La mer Tyrrhénienne'], answer: 1 },
  { id: 'g14', category: 'geographie', difficulty: 3, prompt: 'Quel pays est entièrement enclavé par l’Afrique du Sud ?', choices: ['Le Botswana', 'Le Lesotho', 'L’Eswatini', 'Le Zimbabwe'], answer: 1 },
  { id: 'g15', category: 'geographie', difficulty: 1, prompt: 'Quelle rivière traverse Paris ?', choices: ['La Loire', 'La Seine', 'Le Rhône', 'La Garonne'], answer: 1 },
  { id: 'g16', category: 'geographie', difficulty: 2, prompt: 'Quel pays d’Amérique du Sud a pour langue officielle le portugais ?', choices: ['L’Argentine', 'Le Chili', 'Le Brésil', 'La Colombie'], answer: 2 },
  { id: 'g17', category: 'geographie', difficulty: 2, prompt: 'Quelle capitale européenne est traversée par le Danube ?', choices: ['Madrid', 'Budapest', 'Varsovie', 'Lisbonne'], answer: 1 },
  { id: 'g18', category: 'geographie', difficulty: 1, prompt: 'Quel pays est célèbre pour ses pyramides de Gizeh ?', choices: ['Le Soudan', 'L’Égypte', 'La Libye', 'La Tunisie'], answer: 1 },
  { id: 'g19', category: 'geographie', difficulty: 3, prompt: 'Quel lac africain est le plus grand par sa superficie ?', choices: ['Le lac Tanganyika', 'Le lac Victoria', 'Le lac Malawi', 'Le lac Tchad'], answer: 1 },
  { id: 'g20', category: 'geographie', difficulty: 2, prompt: 'Quelle île est aussi un pays, situé au sud-est de l’Inde ?', choices: ['Madagascar', 'Le Sri Lanka', 'Les Maldives', 'Bornéo'], answer: 1 },
  { id: 'g21', category: 'geographie', difficulty: 1, prompt: 'Quel pays a la forme d’une botte en Europe ?', choices: ['L’Espagne', 'La Grèce', 'L’Italie', 'Le Portugal'], answer: 2 },
  { id: 'g22', category: 'geographie', difficulty: 2, prompt: 'Quelle capitale sud-américaine se situe à la plus haute altitude ?', choices: ['Bogotá', 'Quito', 'La Paz', 'Lima'], answer: 2 },
  { id: 'g23', category: 'geographie', difficulty: 2, prompt: 'Quel détroit sépare l’Espagne du Maroc ?', choices: ['Le détroit de Gibraltar', 'Le détroit de Messine', 'Le détroit du Bosphore', 'Le détroit d’Ormuz'], answer: 0 },
  { id: 'g24', category: 'geographie', difficulty: 1, prompt: 'Quel pays possède le plus grand territoire au monde ?', choices: ['Le Canada', 'La Chine', 'La Russie', 'Les États-Unis'], answer: 2 },
  { id: 'g25', category: 'geographie', difficulty: 3, prompt: 'Quelle chaîne de montagnes borde la côte ouest de l’Amérique du Sud ?', choices: ['Les Rocheuses', 'Les Andes', 'La Sierra Madre', 'Les Appalaches'], answer: 1 },
  { id: 'g26', category: 'geographie', difficulty: 2, prompt: 'Quel pays est séparé en deux parties par le détroit du Bosphore ?', choices: ['La Grèce', 'La Turquie', 'La Bulgarie', 'La Syrie'], answer: 1 },
  { id: 'g27', category: 'geographie', difficulty: 1, prompt: 'Quelle ville est la capitale de l’Espagne ?', choices: ['Barcelone', 'Séville', 'Madrid', 'Valence'], answer: 2 },
  { id: 'g28', category: 'geographie', difficulty: 2, prompt: 'Quel archipel appartient à l’Équateur et est réputé pour sa biodiversité unique ?', choices: ['Les Canaries', 'Les Galápagos', 'Les Açores', 'Les Maldives'], answer: 1 },
  { id: 'g29', category: 'geographie', difficulty: 3, prompt: 'Quel pays compte le plus grand nombre d’îles au monde ?', choices: ['Le Japon', 'La Suède', 'L’Indonésie', 'Les Philippines'], answer: 1 },
  { id: 'g30', category: 'geographie', difficulty: 1, prompt: 'Quel pays a Berne pour capitale ?', choices: ['L’Autriche', 'La Suisse', 'La Belgique', 'Les Pays-Bas'], answer: 1 },

  // --- Art & Littérature -----------------------------------------------------------
  { id: 'a01', category: 'art', difficulty: 1, prompt: 'Qui a peint "La Joconde" ?', choices: ['Michel-Ange', 'Léonard de Vinci', 'Raphaël', 'Botticelli'], answer: 1 },
  { id: 'a02', category: 'art', difficulty: 1, prompt: 'Qui a écrit "Les Misérables" ?', choices: ['Honoré de Balzac', 'Victor Hugo', 'Émile Zola', 'Gustave Flaubert'], answer: 1 },
  { id: 'a03', category: 'art', difficulty: 2, prompt: 'Quel compositeur allemand est devenu sourd avant d’écrire sa 9e symphonie ?', choices: ['Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Johannes Brahms'], answer: 2 },
  { id: 'a04', category: 'art', difficulty: 1, prompt: 'Quel peintre s’est coupé une partie de l’oreille ?', choices: ['Paul Gauguin', 'Vincent van Gogh', 'Claude Monet', 'Edgar Degas'], answer: 1 },
  { id: 'a05', category: 'art', difficulty: 2, prompt: 'Qui a écrit "Roméo et Juliette" ?', choices: ['Christopher Marlowe', 'William Shakespeare', 'Oscar Wilde', 'Charles Dickens'], answer: 1 },
  { id: 'a06', category: 'art', difficulty: 2, prompt: 'Quel mouvement artistique est associé à Claude Monet ?', choices: ['Le cubisme', 'L’impressionnisme', 'Le surréalisme', 'Le fauvisme'], answer: 1 },
  { id: 'a07', category: 'art', difficulty: 1, prompt: 'Quel auteur a créé le personnage de Sherlock Holmes ?', choices: ['Agatha Christie', 'Arthur Conan Doyle', 'Edgar Allan Poe', 'Wilkie Collins'], answer: 1 },
  { id: 'a08', category: 'art', difficulty: 3, prompt: 'Quel peintre espagnol est le fondateur du cubisme avec Georges Braque ?', choices: ['Salvador Dalí', 'Joan Miró', 'Pablo Picasso', 'Diego Vélasquez'], answer: 2 },
  { id: 'a09', category: 'art', difficulty: 2, prompt: 'Quel écrivain français a créé le personnage d’Emma Bovary ?', choices: ['Guy de Maupassant', 'Gustave Flaubert', 'Stendhal', 'Marcel Proust'], answer: 1 },
  { id: 'a10', category: 'art', difficulty: 1, prompt: 'Quel sculpteur a réalisé "Le Penseur" ?', choices: ['Auguste Rodin', 'Antonio Canova', 'Constantin Brâncuși', 'Alberto Giacometti'], answer: 0 },
  { id: 'a11', category: 'art', difficulty: 2, prompt: 'Dans quelle ville se trouve le musée du Louvre ?', choices: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'], answer: 2 },
  { id: 'a12', category: 'art', difficulty: 2, prompt: 'Quel compositeur a écrit "Les Quatre Saisons" ?', choices: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Georg Friedrich Haendel', 'Joseph Haydn'], answer: 0 },
  { id: 'a13', category: 'art', difficulty: 1, prompt: 'Qui a écrit "Le Petit Prince" ?', choices: ['Antoine de Saint-Exupéry', 'Jules Verne', 'Albert Camus', 'Marcel Pagnol'], answer: 0 },
  { id: 'a14', category: 'art', difficulty: 3, prompt: 'Quel peintre flamand a réalisé "La Jeune Fille à la perle" ?', choices: ['Rembrandt', 'Johannes Vermeer', 'Pieter Bruegel', 'Jan van Eyck'], answer: 1 },
  { id: 'a15', category: 'art', difficulty: 2, prompt: 'Quel romancier russe a écrit "Guerre et Paix" ?', choices: ['Fiodor Dostoïevski', 'Léon Tolstoï', 'Anton Tchekhov', 'Nicolas Gogol'], answer: 1 },
  { id: 'a16', category: 'art', difficulty: 1, prompt: 'Quel est le nom du célèbre magicien créé par J.K. Rowling ?', choices: ['Frodo', 'Harry Potter', 'Percy Jackson', 'Gandalf'], answer: 1 },
  { id: 'a17', category: 'art', difficulty: 2, prompt: 'Quel peintre norvégien a réalisé "Le Cri" ?', choices: ['Edvard Munch', 'Gustav Klimt', 'Egon Schiele', 'Caspar David Friedrich'], answer: 0 },
  { id: 'a18', category: 'art', difficulty: 3, prompt: 'Quel poète français a écrit "Les Fleurs du mal" ?', choices: ['Arthur Rimbaud', 'Charles Baudelaire', 'Paul Verlaine', 'Stéphane Mallarmé'], answer: 1 },
  { id: 'a19', category: 'art', difficulty: 1, prompt: 'Quel architecte a conçu la tour Eiffel ?', choices: ['Le Corbusier', 'Gustave Eiffel', 'Georges-Eugène Haussmann', 'Antoni Gaudí'], answer: 1 },
  { id: 'a20', category: 'art', difficulty: 2, prompt: 'Quel ballet célèbre a été composé par Tchaïkovski, avec un lac enchanté ?', choices: ['Casse-Noisette', 'Le Lac des cygnes', 'La Belle au bois dormant', 'Giselle'], answer: 1 },
  { id: 'a21', category: 'art', difficulty: 2, prompt: 'Quel écrivain a créé le détective Hercule Poirot ?', choices: ['Agatha Christie', 'Arthur Conan Doyle', 'Georges Simenon', 'Patricia Highsmith'], answer: 0 },
  { id: 'a22', category: 'art', difficulty: 3, prompt: 'Quel mouvement artistique du 20e siècle est associé à Salvador Dalí ?', choices: ['Le cubisme', 'Le surréalisme', 'Le dadaïsme', 'L’art nouveau'], answer: 1 },
  { id: 'a23', category: 'art', difficulty: 1, prompt: 'Qui a composé l’opéra "La Flûte enchantée" ?', choices: ['Mozart', 'Verdi', 'Wagner', 'Rossini'], answer: 0 },
  { id: 'a24', category: 'art', difficulty: 2, prompt: 'Quel auteur a écrit "1984" ?', choices: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], answer: 1 },
  { id: 'a25', category: 'art', difficulty: 1, prompt: 'Quelle forme d’art combine musique, danse et mise en scène sur une histoire chantée ?', choices: ['Le ballet', 'L’opéra', 'La comédie musicale', 'La pantomime'], answer: 1 },
  { id: 'a26', category: 'art', difficulty: 2, prompt: 'Quel sculpteur italien de la Renaissance a réalisé le "David" ?', choices: ['Donatello', 'Michel-Ange', 'Le Bernin', 'Brunelleschi'], answer: 1 },
  { id: 'a27', category: 'art', difficulty: 3, prompt: 'Quel romancier français est l’auteur de "À la recherche du temps perdu" ?', choices: ['André Gide', 'Marcel Proust', 'Albert Camus', 'Louis-Ferdinand Céline'], answer: 1 },
  { id: 'a28', category: 'art', difficulty: 1, prompt: 'Quel conte met en scène une sirène qui veut devenir humaine ?', choices: ['Cendrillon', 'La Petite Sirène', 'La Belle au bois dormant', 'Blanche-Neige'], answer: 1 },
  { id: 'a29', category: 'art', difficulty: 2, prompt: 'Quel peintre mexicaine est connue pour ses autoportraits puissants ?', choices: ['Remedios Varo', 'Frida Kahlo', 'Tamara de Lempicka', 'Leonora Carrington'], answer: 1 },
  { id: 'a30', category: 'art', difficulty: 2, prompt: 'Quel écrivain français a imaginé le capitaine Nemo et le Nautilus ?', choices: ['Jules Verne', 'H.G. Wells', 'Alexandre Dumas', 'Jules Barbey d’Aurevilly'], answer: 0 },

  // --- Logique (énigmes) -----------------------------------------------------------
  { id: 'l01', category: 'logique', difficulty: 1, prompt: 'Quel nombre complète la suite : 2, 4, 6, 8, ... ?', choices: ['9', '10', '12', '16'], answer: 1 },
  { id: 'l02', category: 'logique', difficulty: 1, prompt: 'Quel nombre complète la suite : 1, 1, 2, 3, 5, 8, ... ?', choices: ['10', '11', '13', '16'], answer: 2 },
  { id: 'l03', category: 'logique', difficulty: 2, prompt: 'Si tous les Zorgs sont des Blips, et que tous les Blips sont bleus, alors ...', choices: ['Tous les Zorgs sont bleus', 'Certains Blips ne sont pas des Zorgs', 'Rien ne peut être déduit', 'Tous les bleus sont des Zorgs'], answer: 0 },
  { id: 'l04', category: 'logique', difficulty: 1, prompt: 'Un train part à 14h00 et arrive à 16h30. Combien de temps a duré le trajet ?', choices: ['2h00', '2h30', '3h00', '1h30'], answer: 1 },
  { id: 'l05', category: 'logique', difficulty: 2, prompt: 'Quel nombre complète la suite : 3, 9, 27, 81, ... ?', choices: ['108', '162', '243', '324'], answer: 2 },
  { id: 'l06', category: 'logique', difficulty: 2, prompt: 'Un fermier a des poules et des lapins, 10 têtes et 28 pattes en tout. Combien y a-t-il de lapins ?', choices: ['4', '6', '8', '10'], answer: 0 },
  { id: 'l07', category: 'logique', difficulty: 1, prompt: 'Quelle lettre vient après E, G, I, K, ... dans cette suite (un saut de 2) ?', choices: ['L', 'M', 'N', 'O'], answer: 1 },
  { id: 'l08', category: 'logique', difficulty: 3, prompt: 'Un train part de Paris vers Lyon à 90 km/h. Au même instant, un autre part de Lyon vers Paris à 60 km/h, sur une voie distante de 450 km. Au bout de combien de temps se croisent-ils ?', choices: ['2h', '2h30', '3h', '3h30'], answer: 2 },
  { id: 'l09', category: 'logique', difficulty: 2, prompt: 'Si je mélange de la peinture bleue et de la peinture jaune, j’obtiens ...', choices: ['Du vert', 'Du violet', 'De l’orange', 'Du gris'], answer: 0 },
  { id: 'l10', category: 'logique', difficulty: 1, prompt: 'Combien de coins possède un cube ?', choices: ['6', '8', '10', '12'], answer: 1 },
  { id: 'l11', category: 'logique', difficulty: 2, prompt: 'Quel mot ne va pas avec les autres : pomme, carotte, banane, poire ?', choices: ['Pomme', 'Carotte', 'Banane', 'Poire'], answer: 1 },
  { id: 'l12', category: 'logique', difficulty: 2, prompt: 'Un escargot grimpe un mur de 10 mètres. Chaque jour il monte 3m et redescend 2m la nuit. En combien de jours atteint-il le sommet ?', choices: ['7', '8', '9', '10'], answer: 1 },
  { id: 'l13', category: 'logique', difficulty: 1, prompt: 'Quel chiffre complète : 5, 10, 15, 20, ... ?', choices: ['22', '24', '25', '30'], answer: 2 },
  { id: 'l14', category: 'logique', difficulty: 3, prompt: 'Dans un code simple, A=1, B=2, C=3... Que vaut le mot "BAD" en somme de ses lettres ?', choices: ['6', '7', '8', '9'], answer: 1 },
  { id: 'l15', category: 'logique', difficulty: 2, prompt: 'Deux pères et deux fils partagent 3 pommes, une chacun. Comment est-ce possible ?', choices: ['Ce sont 3 générations : grand-père, père, fils', 'Une pomme est coupée en deux', 'C’est impossible', 'Ils partagent avec un ami'], answer: 0 },
  { id: 'l16', category: 'logique', difficulty: 1, prompt: 'Quelle forme a 3 côtés ?', choices: ['Un carré', 'Un triangle', 'Un pentagone', 'Un hexagone'], answer: 1 },
  { id: 'l17', category: 'logique', difficulty: 2, prompt: 'Complétez la suite : Z, Y, X, W, ... ?', choices: ['T', 'U', 'V', 'S'], answer: 2 },
  { id: 'l18', category: 'logique', difficulty: 3, prompt: 'Un âne et un mulet portent des sacs. L’âne dit "si tu me donnes un sac, j’en aurai deux fois plus que toi". Le mulet répond "si tu m’en donnes un, on sera à égalité". Combien de sacs porte l’âne ?', choices: ['5', '6', '7', '8'], answer: 2 },
  { id: 'l19', category: 'logique', difficulty: 1, prompt: 'Combien font 7 x 8 ?', choices: ['54', '56', '58', '64'], answer: 1 },
  { id: 'l20', category: 'logique', difficulty: 2, prompt: 'Quel est l’intrus : cercle, carré, sphère, triangle ?', choices: ['Cercle', 'Carré', 'Sphère', 'Triangle'], answer: 2 },
  { id: 'l21', category: 'logique', difficulty: 2, prompt: 'Si hier était vendredi, quel jour sera demain ?', choices: ['Samedi', 'Dimanche', 'Lundi', 'Mardi'], answer: 1 },
  { id: 'l22', category: 'logique', difficulty: 3, prompt: 'Une horloge met 5 secondes à sonner 6 coups. Combien de temps met-elle pour en sonner 12 ?', choices: ['10 secondes', '11 secondes', '12 secondes', '24 secondes'], answer: 1 },
  { id: 'l23', category: 'logique', difficulty: 1, prompt: 'Quel nombre est à la fois pair et premier ?', choices: ['1', '2', '4', '9'], answer: 1 },
  { id: 'l24', category: 'logique', difficulty: 2, prompt: 'Trouvez l’intrus : rouge, bleu, lourd, vert', choices: ['Rouge', 'Bleu', 'Lourd', 'Vert'], answer: 2 },
  { id: 'l25', category: 'logique', difficulty: 3, prompt: 'Combien de carrés peut-on compter sur un plateau d’échecs 8x8, en comptant toutes les tailles ?', choices: ['64', '120', '204', '256'], answer: 2 },
  { id: 'l26', category: 'logique', difficulty: 2, prompt: 'Quel nombre complète : 100, 90, 81, 73, ... (différences qui diminuent de 1) ?', choices: ['64', '65', '66', '67'], answer: 2 },
  { id: 'l27', category: 'logique', difficulty: 1, prompt: 'Quelle direction est opposée au Nord ?', choices: ['Est', 'Ouest', 'Sud', 'Nord-Est'], answer: 2 },
  { id: 'l28', category: 'logique', difficulty: 2, prompt: 'Un code secret inverse l’ordre des lettres. Que donne "LOGIQUE" inversé ?', choices: ['EQUIGOL', 'EUQIGOL', 'ELOGIQU', 'EQIGOLU'], answer: 1 },
  { id: 'l29', category: 'logique', difficulty: 3, prompt: 'Trois interrupteurs commandent trois ampoules dans une autre pièce, que vous ne voyez pas. Vous ne pouvez entrer dans cette pièce qu’une seule fois. Quelle action permet d’identifier à coup sûr chaque interrupteur ?', choices: ['Allumer les trois en même temps', 'Allumer le premier, attendre, l’éteindre, allumer le deuxième, puis entrer', 'Les allumer un par un en regardant à chaque fois', 'C’est impossible'], answer: 1 },
  { id: 'l30', category: 'logique', difficulty: 1, prompt: 'Quel nombre vient avant 0 sur la droite des entiers relatifs ?', choices: ['1', '-1', '10', 'Aucun'], answer: 1 },
];

export function questionsByCategory(category) {
  return QUESTIONS.filter((q) => q.category === category);
}

export function questionsByDifficulty(maxDifficulty) {
  return QUESTIONS.filter((q) => q.difficulty <= maxDifficulty);
}

export const CATEGORIES = ['histoire', 'sciences', 'geographie', 'art', 'logique'];
